fixtures:
  forge_modules:
    beaver:
      repo: "evenup/beaver"
      ref: "1.0.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "3.2.0"
  symlinks:
    auditd: "#{source_dir}"

